
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *        Do not modify: ANY CHANGES WILL GET DISCARDED              *
 *********************************************************************/

module.exports = {
  pluginName: ["silenceDetector","webAudioInput"],
  plugins: {
    silenceDetector: {
      pluginName: "silenceDetector",
      config: [
        /**
         * @type integer
         * @default 15
         */
        "resetCount",
        /**
         * @type integer
         * @default 3
         */
        "pauseCount",
        /**
         * @type float from interval [0, 1]
         * @default 0.1
         */
        "noiseTreshold"
      ],
      defaultValues: {
        resetCount: 15,
        pauseCount: 3,
        noiseTreshold: 0.1
      }
    },
    webAudioInput: {
      pluginName: "webAudioInput",
      config: [
        /**
         * custom encoder parameters (depends on encoder)
         */
        "encoderParams",
        /**
         * size (~ number of audio chunks) for repeat-buffer:
         *
         * during encoding last n chunks get buffered, and on silence (~> end-of-speech)
         * get prepended to the new audio data
         * (in order to prepend audio that is really the next speech utterance but was
         *  still attached to the previous audio due to delay in end-of-speech detection
         *  )
         *
         * @default 3
         */
        "repeatBufferSize",
        /**
         * whether or not request _noise supression_ when capturing/recording audio from microphone
         *
         * NOTE: may not be supported by environment
         *
         * @type boolean
         * @default true
         *
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/noiseSuppression
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/noiseSuppression
         */
        "noiseSuppression",
        /**
         * whether or not request _echo cancellation_ when capturing/recording audio from microphone
         *
         * NOTE: may not be supported by environment
         *
         * @type boolean
         * @default false
         *
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/echoCancellation
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/echoCancellation
         */
        "echoCancellation",
        /**
         * whether or not request _automatic gain (input volume) control_ when capturing/recording audio from microphone
         *
         * NOTE: may not be supported by environment
         *
         * @type boolean
         * @default true
         *
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/autoGainControl
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/autoGainControl
         */
        "autoGainControl",
        /**
         * preferred sample rate for capturing/recording audio from microphone
         *
         * NOTE: may not be supported by environment
         *
         * @type number
         * @default 44100
         *
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/sampleRate
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/sampleRate
         */
        "sampleRate",
        /**
         * preferred number of channels for capturing/recording audio from microphone
         *
         * NOTE: may not be supported by environment for capturing the audio,
         *       but internal recording/encoding will use this setting
         *
         * WARNING: currently, only recording/encoding for 1 channel is supported
         *          (since most speech recognition services require 1 channel/mono audio)
         *
         * @type number
         * @default 1
         *
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/channelCount
         * @see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/channelCount
         */
        "channelCount"
      ],
      defaultValues: {
        encoderParams: null,
        repeatBufferSize: 3,
        noiseSuppression: true,
        echoCancellation: false,
        autoGainControl: true,
        sampleRate: 44100,
        channelCount: 1
      }
    }
  },
  buildConfigs: [
    function(pluginConfig, _runtimeConfig, _pluginBuildConfigs) {
      if(pluginConfig && pluginConfig.encoder){
        var enc = pluginConfig.encoder;
        if(enc === 'wav'){
          return {
            includeModules: ['mmir-plugin-encoder-core/workers/wavEncoder']
          }
        }
        if(enc === 'amr' || enc === 'flac' || enc === 'opus' || enc === 'speex'){
          return {
            includePlugins: [{id: 'mmir-plugin-encoder-'+enc}]
          }
        }
      }
    }
  ],
  /**
   * Known encoders:
   * can be specified via plugin-configuration
   *
   * @exmaple
   *  <pluginName>: {
   *    "encoder": "flac",
   *    ....
   *  }
   *
   * TODO extract this from implementation www/webAudioInput.js::_workerImpl
   */
  defaultEncoders: {
    wav: "mmir-plugin-encoder-core/workers/wavEncoder",
    speex: "mmir-plugin-encoder-speex",
    opus: "mmir-plugin-encoder-opus",
    flac: "mmir-plugin-encoder-flac",
    amr: "mmir-plugin-encoder-amr"
  }
};
