
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

module.exports = {
  pluginName: "webAudioInput",
  config: [
    /** for (simple) end-of-speech detection */
    "silenceDetector"
  ],
  subConfig: {
    silenceDetector: {
      config: [
        /**
         * @type integer, or stringified integer
         * @default 15
         */
        "resetCount",
        /**
         * @type integer, or stringified integer
         * @default 3
         */
        "pauseCount",
        /**
         * @type float of interval [0, 1], or stringified float
         * @default 0.1
         */
        "noiseTreshold"
      ]
    }
  },
  /**
   * Known encoders:
   * can be specified via plugin-configuration
   *
   * @exmaple
   *  <pluginName>: {
   *    "encoder": "flac",
   *    ....
   *  }
   *
   * TODO extract this from implementation www/webAudioInput.js::_workerImpl
   */
  defaultEncoders: {
    wav: "mmir-plugin-encoder-core/workers/recorderWorkerExt",
    flac: "mmir-plugin-encoder-flac",
    amr: "mmir-plugin-encoder-amr"
  }
};
